# relevant docs:
# - http://docs.travis-ci.com/user/languages/groovy/
# - http://blog.freeside.co/2013/02/26/grails-builds-on-travis-ci/

language: groovy

jdk:
  - oraclejdk7

before_install:
- curl -s http://get.sdkman.io | bash
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sdk install grails 3.1.6

script: grails test-app --stacktrace